[53.536653519] 2018-04-12 15:20:50,028 - INFO - launcher: Starting sanity checks
[54.036617279] 2018-04-12 15:20:50,028 - INFO - launcher: Checking for Python 3.5+
[55.539846420] 2018-04-12 15:20:50,030 - INFO - launcher: Checking console encoding
[56.041717529] 2018-04-12 15:20:50,030 - INFO - launcher: Setting console encoding to UTF-8
[56.540250778] 2018-04-12 15:20:50,031 - INFO - launcher: Ensuring we're in the right environment
[58.539867401] 2018-04-12 15:20:50,033 - INFO - launcher: Adding local bins/ folder to path
[59.540987015] 2018-04-12 15:20:50,034 - INFO - launcher: Required checks passed.
[60.042142868] 2018-04-12 15:20:50,034 - INFO - launcher: Optional checks passed.

######################### PRE-RUN SANITY CHECKS PASSED #########################

[2.3946344852447510] 2018-04-12 15:20:52,369 - WARNING - musicbot.config | In config.py::MainThread(8712), line 112 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[2.3951354026794434] 2018-04-12 15:20:52,370 - INFO - musicbot.config | In config.py::MainThread(8712), line 123 in run_checks: Using i18n: config/i18n/en.json
[2.3961358070373535] 2018-04-12 15:20:52,371 - WARNING - musicbot.config | In config.py::MainThread(8712), line 206 in create_empty_file_ifnoexist: Creating config/blacklist.txt
[2.3971350193023682] 2018-04-12 15:20:52,372 - WARNING - musicbot.config | In config.py::MainThread(8712), line 206 in create_empty_file_ifnoexist: Creating config/whitelist.txt
[2.4241552352905273] 2018-04-12 15:20:52,399 - DEBUG - musicbot.config | In config.py::MainThread(8712), line 291 in find_autoplaylist: Copying _autoplaylist.txt to autoplaylist.txt
[2.4281580448150635] 2018-04-12 15:20:52,403 - DEBUG - musicbot.json | In json.py::MainThread(8712), line 8 in __init__: Init JSON obj with config/i18n/en.json
[2.7588918209075928] 2018-04-12 15:20:52,733 - DEBUG - musicbot.bot | In bot.py::MainThread(8712), line 227 in _setup_logging: Set logging level to INFO
[2.7588918209075928] 2018-04-12 15:20:52,733 - INFO - musicbot.bot | In bot.py::MainThread(8712), line 84 in __init__: Starting MusicBot 1.9.7
[2.7603940963745117] 2018-04-12 15:20:52,735 - INFO - musicbot.bot | In bot.py::MainThread(8712), line 90 in __init__: Loaded autoplaylist with 2531 entries
[5.9203178882598877] 2018-04-12 15:20:55,895 - DEBUG - musicbot.bot | In bot.py::MainThread(8712), line 1074 in on_ready: Connection established, ready to go.
[5.9203178882598877] 2018-04-12 15:20:55,895 - DEBUG - musicbot.bot | In bot.py::MainThread(8712), line 339 in _cache_app_info: Caching app info
[6.0844998359680176] 2018-04-12 15:20:56,059 - DEBUG - musicbot.bot | In bot.py::MainThread(8712), line 889 in _scheck_ensure_env: Ensuring data folders exist
[6.0920062065124512] 2018-04-12 15:20:56,066 - DEBUG - musicbot.bot | In bot.py::MainThread(8712), line 905 in _scheck_server_permissions: Checking server permissions
[6.0920062065124512] 2018-04-12 15:20:56,066 - DEBUG - musicbot.bot | In bot.py::MainThread(8712), line 909 in _scheck_autoplaylist: Auditing autoplaylist
[6.0925235748291016] 2018-04-12 15:20:56,067 - DEBUG - musicbot.bot | In bot.py::MainThread(8712), line 913 in _scheck_configs: Validating config
[6.0925235748291016] 2018-04-12 15:20:56,067 - DEBUG - musicbot.config | In config.py::MainThread(8712), line 212 in async_validate: Validating options...
[6.0930068492889404] 2018-04-12 15:20:56,067 - DEBUG - musicbot.config | In config.py::MainThread(8712), line 226 in async_validate: Acquired owner id via API
[6.0930068492889404] 2018-04-12 15:20:56,067 - DEBUG - musicbot.bot | In bot.py::MainThread(8712), line 916 in _scheck_configs: Validating permissions config
[6.0930068492889404] 2018-04-12 15:20:56,067 - DEBUG - musicbot.permissions | In permissions.py::MainThread(8712), line 64 in async_validate: Validating permissions...
[6.0930068492889404] 2018-04-12 15:20:56,067 - DEBUG - musicbot.permissions | In permissions.py::MainThread(8712), line 68 in async_validate: Fixing automatic owner group
[6.0935065746307373] 2018-04-12 15:20:56,068 - INFO - musicbot.bot | In bot.py::MainThread(8712), line 1091 in on_ready: Connected: 433949805413138442/Xc-Mix#1992
[6.0945091247558594] 2018-04-12 15:20:56,069 - INFO - musicbot.bot | In bot.py::MainThread(8712), line 1099 in on_ready: Owner:     150497862575194112/Xcmc#3013

[6.0950081348419189] 2018-04-12 15:20:56,069 - INFO - musicbot.bot | In bot.py::MainThread(8712), line 1102 in on_ready: Server List:
[6.0960083007812500] 2018-04-12 15:20:56,070 - INFO - musicbot.bot | In bot.py::MainThread(8712), line 1105 in on_ready:  - Bot Test
[6.0965096950531006] 2018-04-12 15:20:56,071 - INFO - musicbot.bot | In bot.py::MainThread(8712), line 1151 in on_ready: Not bound to any text channels
[6.0975096225738525] 2018-04-12 15:20:56,072 - INFO - musicbot.bot | In bot.py::MainThread(8712), line 1177 in on_ready: Not autojoining any voice channels
